language: java
sudo: false
before_script: mvn dependency:purge-local-repository -DactTransitively=false -DreResolve=false
script: mvn test -B -Dorg.slf4j.simpleLogger.log.me.andrz.maven.bin=debug
after_success:
  - bash <(curl -s https://codecov.io/bash)
