language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
script: mvn clean test -B -Dorg.slf4j.simpleLogger.log.me.andrz.maven.bin=debug
after_success:
  - bash <(curl -s https://codecov.io/bash)
